### ISSUE TITLE
Command "jay" not found.

### ISSUE THREAD

**Issue by pgegenfurtner** [gatsbymanor/gatsby-theme-kit#4]
I followed the starting from scratch of the getting started (https://www.gatsbymanor.com/docs/quick-start/getting-started) and got to the point where I have to use jay to unmount / mount a new theme.

I had to add the gatsby-jay package myself. I think it should be a dependency in the starter or at least should be mentioned to install it.

**Comment by nodox** [comment]
You might need to run `$ yarn` in your terminal. Followed by `$ yarn run jay ...`. We use this syntax to avoid installing global dependencies however you can install `gatsby-jay` globally and simply run 
`$ jay ...` to complete the mounting and unmounting portion of the tutorial. Let me know if this helps.

**Comment by HighTide2020** [comment]
Maybe this is overkill but I feel like there are a few Issue's around topics like this with `yarn` right now. I also had this Issue, `yarn 1.3.2` `Gatsby 1.9.197` (**almost 2!!**)  `node v9.5.0`. 
Anyways went over a few different situations because I am really interested & excited about this kit!

```
### git clone https://github.com/gatsbymanor/gatsby-theme-kit.git
 cd gatsby-theme-kit
| => yarn 
yarn install v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "gatsby > postcss-cssnext@2.11.0" has unmet peer dependency "caniuse-db@^1.0.30000652".
warning " > react-router-dom@4.2.2" has unmet peer dependency "react@>=15".
warning "gatsby-plugin-react-helmet > react-helmet@5.2.0" has unmet peer dependency "react@>=15.0.0".
warning "gatsby-plugin-sass > sass-loader@4.1.1" has unmet peer dependency "webpack@^2 || ^2.2.0-rc.0 || ^2.1.0-beta || ^1.12.6".
warning " > react-icons@2.2.7" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning " > react-icons@2.2.7" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "react-icons > react-icon-base@2.1.0" has unmet peer dependency "react@*".
warning "react-icons > react-icon-base@2.1.0" has unmet peer dependency "react-dom@*".
warning "react-icons > react-icon-base@2.1.0" has unmet peer dependency "prop-types@*".
warning " > babel-jest@21.2.0" has unmet peer dependency "babel-core@^6.0.0 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0".
warning " > enzyme-adapter-react-16@1.0.2" has unmet peer dependency "react@^16.0.0-0".
warning " > enzyme-adapter-react-16@1.0.2" has unmet peer dependency "react-dom@^16.0.0-0".
warning "enzyme-adapter-react-16 > enzyme-adapter-utils@1.0.1" has unmet peer dependency "react@0.13.x || 0.14.x || ^15.0.0-0 || ^16.0.0-0".
warning " > react-test-renderer@16.0.0" has unmet peer dependency "react@^16.0.0-beta.5".
[4/4] 📃  Building fresh packages...
✨  Done in 168.86s

```
All of these, warnings flag from yarn have been showing up lately, but more so here than other gatsby.js apps. So check all the issues the dependency  & dev dependency. 

`gatsby develop`


looks great, served at localhost:8000
then 


```
yarn run jay unmount starter
yarn run v1.3.2 error Command "jay" not found.info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```



repeated  
then followed the link ### (why not) insert scripts in `package.json `  
then tried ``yarn run jay...`  no luck also

uninstalled repo after some troubleshooting on `yarn run jay..` no luck

then repeated the process from above same errors etc.
also tried `gatsby build` also then `develop ` no luck
`$ rm -rf gatsby-theme-kit`

repeat process
```
$ yarn global add gatsby-jay
$ cd DIRECTOY_NAME
$ jay unmount starter
$ jay add theme
$ jay mount theme
$ gatsby develop
localhost:8000 up and at it.
$yarn global remove gatsby-jay
```
 As this process happened I figured to check issues in the repo. I think there is already a few open issues with yarn around similar situations.Mentioning patch release in 1.4.0 beta and also gatsby.js patch at 2.0 for some of those` yarn `errors.

 Anyways hope to get around to contributing another theme soon. 
Cheers!

**Comment by pgegenfurtner** [comment]
@nodox I did run `yarn` beforehand, but jay is not available. I'm not a yarn user, so I just run the command `yarn add gatsby-jay` and then it worked.

**Comment by jeremybdavis** [comment]
Having the same issue. Made it past the `command jay not found` issue by running `yarn add gatsby-jay`, but now am getting this error when I run `yarn run jay unmount starter`:

`gatsby-theme-kit/node_modules/gatsby-jay/index.js:16
const clone = async (name, sysPath) => {
                    ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
error Command failed with exit code 1.`

**Comment by nodox** [comment]
@jeremybdavis you might've already unmounted the src direction. I must say that the errors are not gracefully handled in this case because I let Git take care of this. PRs with nicer error handling and logging are welcome. 

@hightide2020 thank you for the in depth analysis! I think the tutorial should be rewritten to use a globally installed `gatsby-jay` package. There also might be some dependencies that need be updated. Again, PRs to increase stability are welcome!

If someone is interested in creating a `Dockerfile` that reproduces this error (or providing a fix) that would be great. I did not encounter these errors on my machine. Until, then I will try some changes on my local to see if I can reproduce and solve this error. Thank you all!

**Comment by boylecreations** [comment]
More of the same issues from me as well. Without the command working right, nothing does.

**Comment by nodox** [comment]
Good news, I was able to reproduce the problem locally! Working towards a solution.

**Comment by nodox** [comment]
I believe the tutorial should be correct now...there was a package missing 😅 . Good job @pgegenfurtner.

For posterity, if you see `command 'jay' not found` you might need to run `yarn add gatsby-jay` and add the dependency to your project. 

We need to rethink how to create a base template because these things can get out of date quickly. An approach would be to have `jay init <name>` and that will run a gatsby-cli new project. Jay would then install additional dependencies to get a test setup with Jest+Enzyme ready to go. 

Good next PR for anyone.
